src/main/java/de/maymus/models/User.java
/* 
 * Copyright 2017 brach.kevin@stud.htwk-leipzig.de.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.maymus.models;

import de.maymus.util.Constants;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;
import org.mongodb.morphia.annotations.IndexOptions;
import org.mongodb.morphia.annotations.Indexed;

/**
 *
 * @author vindotrix
 */
@Entity("users")
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    private ObjectId id;

    @Indexed(options = @IndexOptions(unique = true))
    private String username;

    @Indexed(options = @IndexOptions(unique = true))
    private String email;
    private String password;
    private Locale language;
    private LocalDateTime last_online;

    private MovieList movie_favorite;
    private MovieList movie_watchlist;
    private List<MovieList> movie_customLists;

    private SeriesList series_favorite;
    private SeriesList series_watchlist;
    private List<SeriesList> series_customLists;

    private GameList games_favorite;
    private GameList games_watchlist;
    private List<GameList> games_customLists;

    //MORPHIA CONSTRUCTOR
    public User() {
        super();
    }

    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.language = new Locale("de");
        this.movie_favorite = new MovieList(new LinkedList<>(), Constants.FAVORITE, "movie.list.user.favorite.desc", false);
        this.movie_watchlist = new MovieList(new LinkedList<>(), Constants.WATCH, "movie.list.user.watchlist.desc", false);
        this.movie_customLists = new LinkedList<>();
        this.series_favorite = new SeriesList(new LinkedList<>(), Constants.FAVORITE, "");
        this.series_watchlist = new SeriesList(new LinkedList<>(), Constants.WATCH, "");
        this.series_customLists = new LinkedList<>();
        this.games_favorite = new GameList(Constants.FAVORITE, "", false, new LinkedList<>());
        this.games_watchlist = new GameList(Constants.WATCH, "", false, new LinkedList<>());
        this.games_customLists = new LinkedList<>();

    }

    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public LocalDateTime getLast_online() {
        return last_online;
    }

    public void setLast_online(LocalDateTime last_online) {
        this.last_online = last_online;
    }

    public MovieList getMovieFavorite() {
        return movie_favorite;
    }

    public void setMovieFavorite(MovieList favorite) {
        this.movie_favorite = favorite;
    }

    public MovieList getMovieWatchlist() {
        return movie_watchlist;
    }

    public void setMovieWatchlist(MovieList watchlist) {
        this.movie_watchlist = watchlist;
    }

    public List<MovieList> getMovieCustomLists() {
        return movie_customLists;
    }

    public void setMovieCustomLists(List<MovieList> customLists) {
        this.movie_customLists = customLists;
    }

    public SeriesList getSeries_favorite() {
        return series_favorite;
    }

    public void setSeries_favorite(SeriesList series_favorite) {
        this.series_favorite = series_favorite;
    }

    public SeriesList getSeries_watchlist() {
        return series_watchlist;
    }

    public void setSeries_watchlist(SeriesList series_watchlist) {
        this.series_watchlist = series_watchlist;
    }

    public List<SeriesList> getSeries_customLists() {
        return series_customLists;
    }

    public void setSeries_customLists(List<SeriesList> series_customLists) {
        this.series_customLists = series_customLists;
    }

    public GameList getGames_favorite() {
        return games_favorite;
    }

    public void setGames_favorite(GameList games_favorite) {
        this.games_favorite = games_favorite;
    }

    public GameList getGames_watchlist() {
        return games_watchlist;
    }

    public void setGames_watchlist(GameList games_watchlist) {
        this.games_watchlist = games_watchlist;
    }

    public List<GameList> getGames_customLists() {
        return games_customLists;
    }

    public void setGames_customLists(List<GameList> games_customLists) {
        this.games_customLists = games_customLists;
    }

    public Locale getLanguage() {
        return language;
    }

    public void setLanguage(Locale language) {
        this.language = language;
    }

    public String shortUsername() {
        if (username != null && !username.isEmpty()) {
            if (username.length() > 4) {
                return username.substring(0, 2).concat("..");
            } else {
                return username;
            }
        }
        return username;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final User other = (User) obj;
        if (!Objects.equals(this.username, other.username)) {
            return false;
        }
        if (!Objects.equals(this.email, other.email)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "User{" + "id=" + id + ", username=" + username + ", email=" + email + ", password=" + password + ", last_online=" + last_online + '}';
    }

    public String toShortString() {
        return "User{" + "id=" + id + ", username=" + username + ", email=" + email + ", last_online: " + last_online + "}";
    }
}

src/main/webapp/resources/components/card_large.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <composite:interface>
            <composite:attribute name="picture" required="false" default="/resources/images/dummy.png"/>
            <composite:attribute name="picture_lg" required="false" default="/resources/images/dummy.png"/>
            <composite:attribute name="tooltip" required="false" default="xxx"/>
            <composite:attribute name="title" required="true"/>
            <composite:attribute name="o_id" required="true"/>
            <composite:attribute name="story" required="true" />
            <composite:attribute name="rating" required="true" default="Rating: --"/>
            <composite:attribute name="date" required="true" default="Datum: --"/>
            <composite:attribute name="link" required="true"/>
            <composite:attribute name="removeSeries" required="false" default="false"/>
            <composite:attribute name="removeMovie" required="false" default="false"/>
            <composite:attribute name="removeGames" required="false" default="false"/>

        </composite:interface>

        <composite:implementation>
            <b:column col-xs="6" col-sm="4" col-md="3" col-lg="2"  style="padding-left: 10px; padding-right: 10px; margin-bottom: 25px; text-align:  -webkit-center">
                <h:link  outcome="#{cc.attrs.link}" onclick="toggle('progress')">
                    <f:param name="id" value="#{cc.attrs.o_id}"/>

                    <div class="thumbnail thumb">

                        <p:graphicImage value="#{cc.attrs.picture}" class="img-responsive hidden-lg" style="background-image: #{msg['picture.dummy']}" onclick="toggle('progress')"/>
                        <p:graphicImage value="#{cc.attrs.picture_lg}"  class="img-responsive hidden-xs hidden-sm hidden-md"  style="background-image: #{msg['picture.dummy']}" onclick="toggle('progress')"/>

                        <div class="rating">
                            <h:outputText value=" #{cc.attrs.rating}" class="fa fa-star"/>
                        </div>

                        <div class="hover-opaque">
                            <span class="caption thumb_hover" aria-hidden="true">
                                <h:outputText value="#{cc.attrs.title}" class="title"/>
                                <h:outputText value="#{cc.attrs.date}" class="subtitle"/>
                            </span>
                        </div>

                        <p:commandLink action="#{seriesListBean.removeFromList(cc.attrs.o_id)}" update="@all" rendered="#{cc.attrs.removeSeries}">
                            <b:iconAwesome name="times" size="1x" class="close-icon "/>
                        </p:commandLink>
                        <p:commandLink action="#{movieListBean.removeFromList(cc.attrs.o_id)}" update="@all" rendered="#{cc.attrs.removeMovie}">
                            <b:iconAwesome name="times" size="1x" class="close-icon "/>
                        </p:commandLink>
                        <p:commandLink action="#{gameListBean.removeFromList(cc.attrs.o_id)}" update="@all" rendered="#{cc.attrs.removeGames}">
                            <b:iconAwesome name="times" size="1x" class="close-icon "/>
                        </p:commandLink>

                    </div>
                </h:link>
            </b:column>
        </composite:implementation>

    </h:body>
</html>

src/main/webapp/resources/components/card_small.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <composite:interface>
            <composite:attribute name="picture" required="false" default="/resources/dummy.jpg"/>
            <composite:attribute name="tooltip" required="false"/>
            <composite:attribute name="title" required="true"/>
            <composite:attribute name="mov_id" required="false" default=""/>
            <composite:attribute name="subtitle" required="true" default=""/>
            <composite:attribute name="redirect" required="true" default="false"/>
            <composite:attribute name="outcome" required="false" default="/pages/movie/movie.xhtml"/>
        </composite:interface>

        <composite:implementation>
            <h:form rendered="#{cc.attrs.redirect}">
                <div class="thumbnail shadow-link">
                    <h:link  outcome="#{cc.attrs.outcome}" onclick="toggle('progress')" >
                        <f:param name="id" value="#{cc.attrs.mov_id}"/>
                        <p:cache key="#{cc.attrs.picture}"> 
                            <p:graphicImage value="#{cc.attrs.picture}"  class="img-responsive"/>
                        </p:cache>
                        <div class="caption">
                            <h:outputText styleClass="title" value="#{cc.attrs.title}"/>
                            <h:outputText styleClass="subtitle" value="#{cc.attrs.subtitle}"/>
                        </div>
                    </h:link>
                </div>

            </h:form>

            <h:form rendered="#{!cc.attrs.redirect}">
                <div class="thumbnail">
                    <p:cache key="#{cc.attrs.picture}">
                        <p:graphicImage value="#{cc.attrs.picture}"/>
                    </p:cache>
                    <div class="caption">
                        <h:outputText styleClass="title " value="#{cc.attrs.title}"/>
                        <h:outputText styleClass="subtitle " value="#{cc.attrs.subtitle}"/>
                    </div>
                </div>

            </h:form>
        </composite:implementation>
    </h:body>
</html>

src/main/webapp/resources/components/createListDialog.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <composite:interface>
            <composite:attribute name="title" required="true"/>
            <composite:attribute name="type" required="true"/>
            <composite:attribute name="bean" type="java.lang.Object" />




        </composite:interface>

        <composite:implementation>
            <h:form id="fos" style="text-align: left" >
                <b:panelGrid col-spans="12">
                    <b:column rendered="#{sessionBean.loggedIn}" style="padding: 0px; margin: 0px">
                        <p:commandButton  update="@form globalmessages" rendered="#{!cc.attrs.bean.onFavoritelist()}" actionListener="#{cc.attrs.bean.addToFavoriteList()}" class="btn-maymus-primary Dcard-ButtonList" value="#{msg['list.favorite']}" icon="fa fa-square-o"  onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                        <p:commandButton update="@form globalmessages" rendered="#{cc.attrs.bean.onFavoritelist()}" actionListener="#{cc.attrs.bean.removeFromFavoriteList()}" class="btn-maymus-inactive Dcard-ButtonList" value="#{msg['list.favorite']}" icon="fa fa-check-square" onclick="toggle('progress')" onsuccess="toggle('progress')"/>

                        <p:commandButton update="@form globalmessages" rendered="#{!cc.attrs.bean.onWatchlist()}" actionListener="#{cc.attrs.bean.addToWatchList()}" class="btn-maymus-primary Dcard-ButtonList" value="#{msg['list.watchlist']}" icon="fa fa-square-o" onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                        <p:commandButton update="@form globalmessages" rendered="#{cc.attrs.bean.onWatchlist()}" actionListener="#{cc.attrs.bean.removeFromWatchList()}" class="btn-maymus-inactive Dcard-ButtonList" value="#{msg['list.watchlist']}" icon="fa fa-check-square" onclick="toggle('progress')" onsuccess="toggle('progress')"/>

                        <p:repeat value="#{sessionBean.loggedUser.movieCustomLists}" var="abc" rendered="#{cc.attrs.type == 'movie'}">
                            <p:commandButton update="@form globalmessages"
                                             rendered="#{!cc.attrs.bean.onCustomlist(abc)}"
                                             actionListener="#{cc.attrs.bean.addToCustomlist(abc.name)}"
                                             class="btn-maymus-primary Dcard-ButtonList" value="#{abc.name}" icon="fa fa-square-o" onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                            <p:commandButton update="@form globalmessages" rendered="#{cc.attrs.bean.onCustomlist(abc)}" actionListener="#{cc.attrs.bean.removeFromCustomlist(abc.name)}" class="btn-maymus-inactive Dcard-ButtonList" value="#{abc.name}" icon="fa fa-check-square" onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                        </p:repeat>

                        <p:repeat value="#{sessionBean.loggedUser.series_customLists}" var="abc" rendered="#{cc.attrs.type == 'series'}">
                            <p:commandButton update="@form globalmessages"
                                             rendered="#{!cc.attrs.bean.onCustomlist(abc)}"
                                             actionListener="#{cc.attrs.bean.addToCustomlist(abc.name)}"
                                             class="btn-maymus-primary Dcard-ButtonList" value="#{abc.name}" icon="fa fa-square-o" onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                            <p:commandButton update="@form globalmessages" rendered="#{cc.attrs.bean.onCustomlist(abc)}" actionListener="#{cc.attrs.bean.removeFromCustomlist(abc.name)}" class="btn-maymus-inactive Dcard-ButtonList" value="#{abc.name}" icon="fa fa-check-square" onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                        </p:repeat>

                        <p:repeat value="#{sessionBean.loggedUser.games_customLists}" var="abc" rendered="#{cc.attrs.type == 'games'}">
                            <p:commandButton update="@form globalmessages"
                                             rendered="#{!cc.attrs.bean.onCustomlist(abc)}"
                                             actionListener="#{cc.attrs.bean.addToCustomlist(abc.name)}"
                                             class="btn-maymus-primary Dcard-ButtonList" value="#{abc.name}" icon="fa fa-square-o" onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                            <p:commandButton update="@form globalmessages" rendered="#{cc.attrs.bean.onCustomlist(abc)}" actionListener="#{cc.attrs.bean.removeFromCustomlist(abc.name)}" class="btn-maymus-inactive Dcard-ButtonList" value="#{abc.name}" icon="fa fa-check-square" onclick="toggle('progress')" onsuccess="toggle('progress')"/>
                        </p:repeat>

                        <p:commandButton update="@form globalmessages" onclick="PF('dlg1').show();" icon="fa fa-plus" value="#{msg['customList.add.button']}" class="btn-maymus-primary Dcard-ButtonList"/>
                    </b:column>
                    <b:column rendered="#{!sessionBean.loggedIn}" style="padding: 0px; margin: 0px">
                        <b:label   value="#{msg['user.lists.login.message']}" class="login-hint" style="margin-bottom: 5px; border-radius: 0px; display: block; font-size: 1.2em; white-space: initial"/>
                        <p:button class="btn-maymus-primary Dcard-ButtonList" disabled="true" value="#{msg['list.favorite']}" icon="fa fa-square-o"/>
                        <p:button class="btn-maymus-primary Dcard-ButtonList" disabled="true" value="#{msg['list.watchlist']}" icon="fa fa-square-o"/>
                        <p:button  icon="fa fa-plus" disabled="true" value="#{msg['customList.add.button']}" class="btn-maymus-primary Dcard-ButtonList"/>

                    </b:column>

                </b:panelGrid>
            </h:form>

            <p:dialog header="#{cc.attrs.title}" id="d_dialog" widgetVar="dlg1" style="border-radius: 0px" responsive="true" modal="true" rendered="#{sessionBean.loggedIn}">


                <h:form id="d_form" >
                    <b:panel collapsible="false" class="customList" col-xs="12" >
                        <b:column col-xs="10" offset-xs="1">
                            <h:outputText value="#{msg['customList.add.input.name']}" class="customList-title"/>
                            <b:inputText id="input_name" value="#{cc.attrs.bean.customListName}">
                                <f:validator validatorId="createListValidation" />
                                <f:attribute name="loggedUser" value="#{sessionBean.loggedUser}"/>
                                <f:attribute name="type" value="#{cc.attrs.type}"/>

                            </b:inputText>
                            <b:message id="input_msg" for="@previous" showIcon="false" showDetail="true" style="text-align: left"/>

                            <h:outputText value="#{msg['customList.add.input.description']}" class="customList-title"/>
                            <b:inputTextarea value="#{cc.attrs.bean.customListDesc}" />
                            <b:message for="create_list" showIcon="false" showDetail="true" style="text-align: left"/>

                            <b:column col-xs="5" style="text-align: left">
                                <h:outputText value="#{msg['customList.share.label']}" style="font-weight: bold"/>


                            </b:column>
                            <b:column col-xs="7" style="text-align: right">
                                <p:selectBooleanCheckbox value="#{cc.attrs.bean.customListPublicity}" />
                            </b:column>
                            <h:outputText value="#{msg['customList.share.info']}" style="font-size: 13px; font-style: italic"/>


                            <p:commandButton update="#{cc.attrs.id}:fos @form globalmessages" id="create_list" value="#{msg['customList.add.button']}" style="width: 100%; margin-top: 15px"
                                             class="btn-maymus-primary" action="#{cc.attrs.bean.createNewCustomList}"
                                             oncomplete="if (!args.validationFailed) PF('dlg1').hide()"/>
                        </b:column>
                    </b:panel>
                </h:form>
            </p:dialog>

        </composite:implementation>

    </h:body>
</html>

src/main/webapp/resources/components/editListDialog.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:body>
        <composite:interface>
            <composite:attribute name="bean" type="java.lang.Object" />



        </composite:interface>

        <composite:implementation>

            <p:dialog header="#{msg['dialog.customList.header']}" id="editList" responsive="true" widgetVar="editList" resizable="false" rendered="#{sessionBean.loggedIn}" modal="true" draggable="true">

                <h:form id="d_form" style="width: 100%">
                    <p:defaultCommand target="edit_list"/>
                    <b:panel collapsible="false" class="customList" col-xs="12" style="font-size: 18px;" >
                        <b:message id="input_msg" for="input_name" showIcon="false" showDetail="true" style="text-align: left;margin-bottom: 15px !important"/>

                        <b:column col-xs="12" col-md="5">
                            <h:outputLabel value="#{msg['customList.add.input.name']}"/>
                        </b:column>
                        <b:column col-xs="12" col-md="7">
                            <b:inputText value="#{cc.attrs.bean.editName}" id="input_name">
                                <f:validator validatorId="editListValidator" />
                                <f:attribute name="oldName" value="#{cc.attrs.bean.listname}"/>
                                <f:attribute name="loggedUser" value="#{sessionBean.loggedUser}"/>
                            </b:inputText>


                        </b:column>
                        <b:column col-xs="12" col-md="5" >
                            <h:outputLabel value="#{msg['customList.add.input.description']}"/>
                        </b:column>
                        <b:column col-xs="12" col-md="7">
                            <b:inputTextarea value="#{cc.attrs.bean.editDesc}"/>
                        </b:column>
                        <b:column col-xs="12" col-md="5" >
                            <h:outputLabel value="#{msg['customList.share.label']}"/>
                        </b:column>
                        <b:column col-xs="12" col-md="7">
                            <p:selectBooleanCheckbox value="#{cc.attrs.bean.editPublicity}"/>
                        </b:column>
                        <b:column col-xs="12">
                            <b:column col-xs="12" col-md="4" style="margin: 0px; padding: 5px">
                                <b:commandButton update="d_form globalmessages" id="cancle_list" value="#{msg['dialog.customList.btn.cancle']}" style="width: 100%; bottom: 0px"
                                                 class="btn-maymus-primary" onclick="PF('editList').hide()" process="@this" immediate="true"/>
                            </b:column>
                            <b:column col-xs="12" col-md="4"  style="margin: 0px; padding: 5px">
                                <p:commandButton update="d_form globalmessages" value="#{msg['dialog.customList.btn.remove']}" action="#{cc.attrs.bean.removeList()}" class="btn btn-maymus-primary" style="width: 100%; bottom: 0px" process="@this">
                                    <p:confirm header="#{msg['dialog.confirm.header.delete']}" message="#{msg['dialog.confirm.msg.delete']}" icon="ui-icon-alert"/>
                                </p:commandButton>

                            </b:column>
                            <b:column col-xs="12" col-md="4"  style="margin: 0px; padding: 5px">
                                <b:commandButton update="d_form globalmessages" id="edit_list" value="#{msg['dialog.customList.btn.edit']}" style="width: 100%; bottom: 0px"
                                                 class="btn-maymus-primary" action="#{cc.attrs.bean.editList()}" onclick="toggle('progress')"
                                                 oncomplete="if (!args.validationFailed) PF('editList').hide()">
                                </b:commandButton>
                            </b:column>

                        </b:column>
                    </b:panel>
                </h:form>
            </p:dialog>



        </composite:implementation>

    </h:body>
</html>

src/main/webapp/resources/components/social_component.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:composite="http://java.sun.com/jsf/composite"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">
    <h:body>
        <composite:interface>
            <composite:attribute name="text" required="true" default=""/>
        </composite:interface>

        <composite:implementation>

            <b:socialShare shares="twitter,facebook,email,googleplus"
                           show-label="false" show-count="false"
                           text="#{cc.attrs.text}"
                           block-message="#{msg['share.block.text']}"

                           />

        </composite:implementation>
    </h:body>
</html>